#!/usr/bin/python

import sys
import json
import re
import urllib

load = open(sys.argv[1])

i=0
for p in json.load(load):
    if re.match('https?://', p):
        continue

    i+=1

    # if i > 1:
    #     break

    res = urllib.urlopen('https://api.wordpress.org/plugins/info/1.0/%s.json' % p)
    plugin = json.loads(res.read())

    try:
        if plugin and plugin['downloaded']:
            print '%d valid (%s@%d)' % (i, p, plugin['downloaded'])
            with open('valid', 'a') as f:
                f.write('%s@%s' % (p, plugin['downloaded']) + '\n')
        else:
            print '%d invalid (%s)' % (i, p)
    except:
        print '%d invalid (%s)' % (i, p)
        pass
